from datetime import datetime, date
from ..extensions import db


class Transaction(db.Model):
    __tablename__ = "transaction"

    id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.Integer, db.ForeignKey("account.id"), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey("category.id"))
    amount = db.Column(db.Float, nullable=False)
    type = db.Column(db.String(20), nullable=False)  # income or expense
    description = db.Column(db.String(500))
    date = db.Column(db.Date, nullable=False, default=date.today)
    # Set when this transaction was generated by a recurring rule
    recurring_transaction_id = db.Column(db.Integer, db.ForeignKey("recurring_transaction.id"))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "id": self.id,
            "account_id": self.account_id,
            "account_name": self.account.name if self.account else None,
            "category_id": self.category_id,
            "category_name": self.category.name if self.category else None,
            "category_color": self.category.color if self.category else None,
            "amount": self.amount,
            "type": self.type,
            "description": self.description,
            "date": self.date.isoformat() if self.date else None,
            "recurring_transaction_id": self.recurring_transaction_id,
            "created_at": self.created_at.isoformat(),
        }
